/**
 *
 *  CourseEnrollments.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "CourseEnrollments.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::myserver;

const std::string CourseEnrollments::Cols::_id = "\"id\"";
const std::string CourseEnrollments::Cols::_user_id = "\"user_id\"";
const std::string CourseEnrollments::Cols::_course_id = "\"course_id\"";
const std::string CourseEnrollments::Cols::_completion_percentage = "\"completion_percentage\"";
const std::string CourseEnrollments::Cols::_is_completed = "\"is_completed\"";
const std::string CourseEnrollments::Cols::_enrolled_at = "\"enrolled_at\"";
const std::string CourseEnrollments::Cols::_completed_at = "\"completed_at\"";
const std::string CourseEnrollments::Cols::_last_accessed_at = "\"last_accessed_at\"";
const std::string CourseEnrollments::primaryKeyName = "id";
const bool CourseEnrollments::hasPrimaryKey = true;
const std::string CourseEnrollments::tableName = "\"course_enrollments\"";

const std::vector<typename CourseEnrollments::MetaData> CourseEnrollments::metaData_={
{"id","std::string","text",0,0,1,1},
{"user_id","std::string","text",0,0,0,1},
{"course_id","std::string","text",0,0,0,1},
{"completion_percentage","int32_t","integer",4,0,0,0},
{"is_completed","bool","boolean",1,0,0,0},
{"enrolled_at","::trantor::Date","timestamp with time zone",0,0,0,0},
{"completed_at","::trantor::Date","timestamp with time zone",0,0,0,0},
{"last_accessed_at","::trantor::Date","timestamp with time zone",0,0,0,0}
};
const std::string &CourseEnrollments::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
CourseEnrollments::CourseEnrollments(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<std::string>(r["id"].as<std::string>());
        }
        if(!r["user_id"].isNull())
        {
            userId_=std::make_shared<std::string>(r["user_id"].as<std::string>());
        }
        if(!r["course_id"].isNull())
        {
            courseId_=std::make_shared<std::string>(r["course_id"].as<std::string>());
        }
        if(!r["completion_percentage"].isNull())
        {
            completionPercentage_=std::make_shared<int32_t>(r["completion_percentage"].as<int32_t>());
        }
        if(!r["is_completed"].isNull())
        {
            isCompleted_=std::make_shared<bool>(r["is_completed"].as<bool>());
        }
        if(!r["enrolled_at"].isNull())
        {
            auto timeStr = r["enrolled_at"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                enrolledAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        if(!r["completed_at"].isNull())
        {
            auto timeStr = r["completed_at"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                completedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        if(!r["last_accessed_at"].isNull())
        {
            auto timeStr = r["last_accessed_at"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                lastAccessedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 8 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            userId_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            courseId_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            completionPercentage_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            isCompleted_=std::make_shared<bool>(r[index].as<bool>());
        }
        index = offset + 5;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                enrolledAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        index = offset + 6;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                completedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        index = offset + 7;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                lastAccessedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }

}

CourseEnrollments::CourseEnrollments(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 8)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            userId_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            courseId_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            completionPercentage_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[3]].asInt64());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            isCompleted_=std::make_shared<bool>(pJson[pMasqueradingVector[4]].asBool());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[5]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                enrolledAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[6]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                completedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[7]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                lastAccessedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

CourseEnrollments::CourseEnrollments(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<std::string>(pJson["id"].asString());
        }
    }
    if(pJson.isMember("user_id"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["user_id"].isNull())
        {
            userId_=std::make_shared<std::string>(pJson["user_id"].asString());
        }
    }
    if(pJson.isMember("course_id"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["course_id"].isNull())
        {
            courseId_=std::make_shared<std::string>(pJson["course_id"].asString());
        }
    }
    if(pJson.isMember("completion_percentage"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["completion_percentage"].isNull())
        {
            completionPercentage_=std::make_shared<int32_t>((int32_t)pJson["completion_percentage"].asInt64());
        }
    }
    if(pJson.isMember("is_completed"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["is_completed"].isNull())
        {
            isCompleted_=std::make_shared<bool>(pJson["is_completed"].asBool());
        }
    }
    if(pJson.isMember("enrolled_at"))
    {
        dirtyFlag_[5]=true;
        if(!pJson["enrolled_at"].isNull())
        {
            auto timeStr = pJson["enrolled_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                enrolledAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("completed_at"))
    {
        dirtyFlag_[6]=true;
        if(!pJson["completed_at"].isNull())
        {
            auto timeStr = pJson["completed_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                completedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("last_accessed_at"))
    {
        dirtyFlag_[7]=true;
        if(!pJson["last_accessed_at"].isNull())
        {
            auto timeStr = pJson["last_accessed_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                lastAccessedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

void CourseEnrollments::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 8)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            userId_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            courseId_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            completionPercentage_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[3]].asInt64());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            isCompleted_=std::make_shared<bool>(pJson[pMasqueradingVector[4]].asBool());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[5]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                enrolledAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[6]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                completedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[7]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                lastAccessedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

void CourseEnrollments::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<std::string>(pJson["id"].asString());
        }
    }
    if(pJson.isMember("user_id"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["user_id"].isNull())
        {
            userId_=std::make_shared<std::string>(pJson["user_id"].asString());
        }
    }
    if(pJson.isMember("course_id"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["course_id"].isNull())
        {
            courseId_=std::make_shared<std::string>(pJson["course_id"].asString());
        }
    }
    if(pJson.isMember("completion_percentage"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["completion_percentage"].isNull())
        {
            completionPercentage_=std::make_shared<int32_t>((int32_t)pJson["completion_percentage"].asInt64());
        }
    }
    if(pJson.isMember("is_completed"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["is_completed"].isNull())
        {
            isCompleted_=std::make_shared<bool>(pJson["is_completed"].asBool());
        }
    }
    if(pJson.isMember("enrolled_at"))
    {
        dirtyFlag_[5] = true;
        if(!pJson["enrolled_at"].isNull())
        {
            auto timeStr = pJson["enrolled_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                enrolledAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("completed_at"))
    {
        dirtyFlag_[6] = true;
        if(!pJson["completed_at"].isNull())
        {
            auto timeStr = pJson["completed_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                completedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("last_accessed_at"))
    {
        dirtyFlag_[7] = true;
        if(!pJson["last_accessed_at"].isNull())
        {
            auto timeStr = pJson["last_accessed_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                lastAccessedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

const std::string &CourseEnrollments::getValueOfId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<std::string> &CourseEnrollments::getId() const noexcept
{
    return id_;
}
void CourseEnrollments::setId(const std::string &pId) noexcept
{
    id_ = std::make_shared<std::string>(pId);
    dirtyFlag_[0] = true;
}
void CourseEnrollments::setId(std::string &&pId) noexcept
{
    id_ = std::make_shared<std::string>(std::move(pId));
    dirtyFlag_[0] = true;
}
const typename CourseEnrollments::PrimaryKeyType & CourseEnrollments::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const std::string &CourseEnrollments::getValueOfUserId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(userId_)
        return *userId_;
    return defaultValue;
}
const std::shared_ptr<std::string> &CourseEnrollments::getUserId() const noexcept
{
    return userId_;
}
void CourseEnrollments::setUserId(const std::string &pUserId) noexcept
{
    userId_ = std::make_shared<std::string>(pUserId);
    dirtyFlag_[1] = true;
}
void CourseEnrollments::setUserId(std::string &&pUserId) noexcept
{
    userId_ = std::make_shared<std::string>(std::move(pUserId));
    dirtyFlag_[1] = true;
}

const std::string &CourseEnrollments::getValueOfCourseId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(courseId_)
        return *courseId_;
    return defaultValue;
}
const std::shared_ptr<std::string> &CourseEnrollments::getCourseId() const noexcept
{
    return courseId_;
}
void CourseEnrollments::setCourseId(const std::string &pCourseId) noexcept
{
    courseId_ = std::make_shared<std::string>(pCourseId);
    dirtyFlag_[2] = true;
}
void CourseEnrollments::setCourseId(std::string &&pCourseId) noexcept
{
    courseId_ = std::make_shared<std::string>(std::move(pCourseId));
    dirtyFlag_[2] = true;
}

const int32_t &CourseEnrollments::getValueOfCompletionPercentage() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(completionPercentage_)
        return *completionPercentage_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &CourseEnrollments::getCompletionPercentage() const noexcept
{
    return completionPercentage_;
}
void CourseEnrollments::setCompletionPercentage(const int32_t &pCompletionPercentage) noexcept
{
    completionPercentage_ = std::make_shared<int32_t>(pCompletionPercentage);
    dirtyFlag_[3] = true;
}
void CourseEnrollments::setCompletionPercentageToNull() noexcept
{
    completionPercentage_.reset();
    dirtyFlag_[3] = true;
}

const bool &CourseEnrollments::getValueOfIsCompleted() const noexcept
{
    static const bool defaultValue = bool();
    if(isCompleted_)
        return *isCompleted_;
    return defaultValue;
}
const std::shared_ptr<bool> &CourseEnrollments::getIsCompleted() const noexcept
{
    return isCompleted_;
}
void CourseEnrollments::setIsCompleted(const bool &pIsCompleted) noexcept
{
    isCompleted_ = std::make_shared<bool>(pIsCompleted);
    dirtyFlag_[4] = true;
}
void CourseEnrollments::setIsCompletedToNull() noexcept
{
    isCompleted_.reset();
    dirtyFlag_[4] = true;
}

const ::trantor::Date &CourseEnrollments::getValueOfEnrolledAt() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(enrolledAt_)
        return *enrolledAt_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &CourseEnrollments::getEnrolledAt() const noexcept
{
    return enrolledAt_;
}
void CourseEnrollments::setEnrolledAt(const ::trantor::Date &pEnrolledAt) noexcept
{
    enrolledAt_ = std::make_shared<::trantor::Date>(pEnrolledAt);
    dirtyFlag_[5] = true;
}
void CourseEnrollments::setEnrolledAtToNull() noexcept
{
    enrolledAt_.reset();
    dirtyFlag_[5] = true;
}

const ::trantor::Date &CourseEnrollments::getValueOfCompletedAt() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(completedAt_)
        return *completedAt_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &CourseEnrollments::getCompletedAt() const noexcept
{
    return completedAt_;
}
void CourseEnrollments::setCompletedAt(const ::trantor::Date &pCompletedAt) noexcept
{
    completedAt_ = std::make_shared<::trantor::Date>(pCompletedAt);
    dirtyFlag_[6] = true;
}
void CourseEnrollments::setCompletedAtToNull() noexcept
{
    completedAt_.reset();
    dirtyFlag_[6] = true;
}

const ::trantor::Date &CourseEnrollments::getValueOfLastAccessedAt() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(lastAccessedAt_)
        return *lastAccessedAt_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &CourseEnrollments::getLastAccessedAt() const noexcept
{
    return lastAccessedAt_;
}
void CourseEnrollments::setLastAccessedAt(const ::trantor::Date &pLastAccessedAt) noexcept
{
    lastAccessedAt_ = std::make_shared<::trantor::Date>(pLastAccessedAt);
    dirtyFlag_[7] = true;
}
void CourseEnrollments::setLastAccessedAtToNull() noexcept
{
    lastAccessedAt_.reset();
    dirtyFlag_[7] = true;
}

void CourseEnrollments::updateId(const uint64_t id)
{
}

const std::vector<std::string> &CourseEnrollments::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "id",
        "user_id",
        "course_id",
        "completion_percentage",
        "is_completed",
        "enrolled_at",
        "completed_at",
        "last_accessed_at"
    };
    return inCols;
}

void CourseEnrollments::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getId())
        {
            binder << getValueOfId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getUserId())
        {
            binder << getValueOfUserId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getCourseId())
        {
            binder << getValueOfCourseId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getCompletionPercentage())
        {
            binder << getValueOfCompletionPercentage();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getIsCompleted())
        {
            binder << getValueOfIsCompleted();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getEnrolledAt())
        {
            binder << getValueOfEnrolledAt();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getCompletedAt())
        {
            binder << getValueOfCompletedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getLastAccessedAt())
        {
            binder << getValueOfLastAccessedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> CourseEnrollments::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[0])
    {
        ret.push_back(getColumnName(0));
    }
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if(dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    if(dirtyFlag_[6])
    {
        ret.push_back(getColumnName(6));
    }
    if(dirtyFlag_[7])
    {
        ret.push_back(getColumnName(7));
    }
    return ret;
}

void CourseEnrollments::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getId())
        {
            binder << getValueOfId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getUserId())
        {
            binder << getValueOfUserId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getCourseId())
        {
            binder << getValueOfCourseId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getCompletionPercentage())
        {
            binder << getValueOfCompletionPercentage();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getIsCompleted())
        {
            binder << getValueOfIsCompleted();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getEnrolledAt())
        {
            binder << getValueOfEnrolledAt();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getCompletedAt())
        {
            binder << getValueOfCompletedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getLastAccessedAt())
        {
            binder << getValueOfLastAccessedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value CourseEnrollments::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getUserId())
    {
        ret["user_id"]=getValueOfUserId();
    }
    else
    {
        ret["user_id"]=Json::Value();
    }
    if(getCourseId())
    {
        ret["course_id"]=getValueOfCourseId();
    }
    else
    {
        ret["course_id"]=Json::Value();
    }
    if(getCompletionPercentage())
    {
        ret["completion_percentage"]=getValueOfCompletionPercentage();
    }
    else
    {
        ret["completion_percentage"]=Json::Value();
    }
    if(getIsCompleted())
    {
        ret["is_completed"]=getValueOfIsCompleted();
    }
    else
    {
        ret["is_completed"]=Json::Value();
    }
    if(getEnrolledAt())
    {
        ret["enrolled_at"]=getEnrolledAt()->toDbStringLocal();
    }
    else
    {
        ret["enrolled_at"]=Json::Value();
    }
    if(getCompletedAt())
    {
        ret["completed_at"]=getCompletedAt()->toDbStringLocal();
    }
    else
    {
        ret["completed_at"]=Json::Value();
    }
    if(getLastAccessedAt())
    {
        ret["last_accessed_at"]=getLastAccessedAt()->toDbStringLocal();
    }
    else
    {
        ret["last_accessed_at"]=Json::Value();
    }
    return ret;
}

std::string CourseEnrollments::toString() const
{
    return toJson().toStyledString();
}

Json::Value CourseEnrollments::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 8)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getUserId())
            {
                ret[pMasqueradingVector[1]]=getValueOfUserId();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getCourseId())
            {
                ret[pMasqueradingVector[2]]=getValueOfCourseId();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getCompletionPercentage())
            {
                ret[pMasqueradingVector[3]]=getValueOfCompletionPercentage();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getIsCompleted())
            {
                ret[pMasqueradingVector[4]]=getValueOfIsCompleted();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[5].empty())
        {
            if(getEnrolledAt())
            {
                ret[pMasqueradingVector[5]]=getEnrolledAt()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[5]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[6].empty())
        {
            if(getCompletedAt())
            {
                ret[pMasqueradingVector[6]]=getCompletedAt()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[6]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[7].empty())
        {
            if(getLastAccessedAt())
            {
                ret[pMasqueradingVector[7]]=getLastAccessedAt()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[7]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getUserId())
    {
        ret["user_id"]=getValueOfUserId();
    }
    else
    {
        ret["user_id"]=Json::Value();
    }
    if(getCourseId())
    {
        ret["course_id"]=getValueOfCourseId();
    }
    else
    {
        ret["course_id"]=Json::Value();
    }
    if(getCompletionPercentage())
    {
        ret["completion_percentage"]=getValueOfCompletionPercentage();
    }
    else
    {
        ret["completion_percentage"]=Json::Value();
    }
    if(getIsCompleted())
    {
        ret["is_completed"]=getValueOfIsCompleted();
    }
    else
    {
        ret["is_completed"]=Json::Value();
    }
    if(getEnrolledAt())
    {
        ret["enrolled_at"]=getEnrolledAt()->toDbStringLocal();
    }
    else
    {
        ret["enrolled_at"]=Json::Value();
    }
    if(getCompletedAt())
    {
        ret["completed_at"]=getCompletedAt()->toDbStringLocal();
    }
    else
    {
        ret["completed_at"]=Json::Value();
    }
    if(getLastAccessedAt())
    {
        ret["last_accessed_at"]=getLastAccessedAt()->toDbStringLocal();
    }
    else
    {
        ret["last_accessed_at"]=Json::Value();
    }
    return ret;
}

bool CourseEnrollments::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    if(pJson.isMember("user_id"))
    {
        if(!validJsonOfField(1, "user_id", pJson["user_id"], err, true))
            return false;
    }
    else
    {
        err="The user_id column cannot be null";
        return false;
    }
    if(pJson.isMember("course_id"))
    {
        if(!validJsonOfField(2, "course_id", pJson["course_id"], err, true))
            return false;
    }
    else
    {
        err="The course_id column cannot be null";
        return false;
    }
    if(pJson.isMember("completion_percentage"))
    {
        if(!validJsonOfField(3, "completion_percentage", pJson["completion_percentage"], err, true))
            return false;
    }
    if(pJson.isMember("is_completed"))
    {
        if(!validJsonOfField(4, "is_completed", pJson["is_completed"], err, true))
            return false;
    }
    if(pJson.isMember("enrolled_at"))
    {
        if(!validJsonOfField(5, "enrolled_at", pJson["enrolled_at"], err, true))
            return false;
    }
    if(pJson.isMember("completed_at"))
    {
        if(!validJsonOfField(6, "completed_at", pJson["completed_at"], err, true))
            return false;
    }
    if(pJson.isMember("last_accessed_at"))
    {
        if(!validJsonOfField(7, "last_accessed_at", pJson["last_accessed_at"], err, true))
            return false;
    }
    return true;
}
bool CourseEnrollments::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                           const std::vector<std::string> &pMasqueradingVector,
                                                           std::string &err)
{
    if(pMasqueradingVector.size() != 8)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[2] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[5].empty())
      {
          if(pJson.isMember(pMasqueradingVector[5]))
          {
              if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[6].empty())
      {
          if(pJson.isMember(pMasqueradingVector[6]))
          {
              if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[7].empty())
      {
          if(pJson.isMember(pMasqueradingVector[7]))
          {
              if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool CourseEnrollments::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("user_id"))
    {
        if(!validJsonOfField(1, "user_id", pJson["user_id"], err, false))
            return false;
    }
    if(pJson.isMember("course_id"))
    {
        if(!validJsonOfField(2, "course_id", pJson["course_id"], err, false))
            return false;
    }
    if(pJson.isMember("completion_percentage"))
    {
        if(!validJsonOfField(3, "completion_percentage", pJson["completion_percentage"], err, false))
            return false;
    }
    if(pJson.isMember("is_completed"))
    {
        if(!validJsonOfField(4, "is_completed", pJson["is_completed"], err, false))
            return false;
    }
    if(pJson.isMember("enrolled_at"))
    {
        if(!validJsonOfField(5, "enrolled_at", pJson["enrolled_at"], err, false))
            return false;
    }
    if(pJson.isMember("completed_at"))
    {
        if(!validJsonOfField(6, "completed_at", pJson["completed_at"], err, false))
            return false;
    }
    if(pJson.isMember("last_accessed_at"))
    {
        if(!validJsonOfField(7, "last_accessed_at", pJson["last_accessed_at"], err, false))
            return false;
    }
    return true;
}
bool CourseEnrollments::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                         const std::vector<std::string> &pMasqueradingVector,
                                                         std::string &err)
{
    if(pMasqueradingVector.size() != 8)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
      if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
      {
          if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
              return false;
      }
      if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
      {
          if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, false))
              return false;
      }
      if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
      {
          if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool CourseEnrollments::validJsonOfField(size_t index,
                                         const std::string &fieldName,
                                         const Json::Value &pJson,
                                         std::string &err,
                                         bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isBool())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 5:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 6:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 7:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
