/**
 *
 *  CourseVideos.h
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#pragma once
#include <drogon/orm/Result.h>
#include <drogon/orm/Row.h>
#include <drogon/orm/Field.h>
#include <drogon/orm/SqlBinder.h>
#include <drogon/orm/Mapper.h>
#include <drogon/orm/BaseBuilder.h>
#ifdef __cpp_impl_coroutine
#include <drogon/orm/CoroMapper.h>
#endif
#include <trantor/utils/Date.h>
#include <trantor/utils/Logger.h>
#include <json/json.h>
#include <string>
#include <string_view>
#include <memory>
#include <vector>
#include <tuple>
#include <stdint.h>
#include <iostream>

namespace drogon
{
namespace orm
{
class DbClient;
using DbClientPtr = std::shared_ptr<DbClient>;
}
}
namespace drogon_model
{
namespace myserver
{

class CourseVideos
{
  public:
    struct Cols
    {
        static const std::string _id;
        static const std::string _course_id;
        static const std::string _chapter_id;
        static const std::string _author_id;
        static const std::string _title;
        static const std::string _description;
        static const std::string _order;
        static const std::string _video_filename;
        static const std::string _video_path;
        static const std::string _duration;
        static const std::string _duration_seconds;
        static const std::string _cover_path;
        static const std::string _has_subtitles;
        static const std::string _has_notes;
        static const std::string _views_count;
        static const std::string _likes_count;
        static const std::string _is_approved;
        static const std::string _approved_by;
        static const std::string _approved_at;
        static const std::string _uploaded_by;
        static const std::string _created_at;
        static const std::string _updated_at;
        static const std::string _last_accessed_at;
    };

    static const int primaryKeyNumber;
    static const std::string tableName;
    static const bool hasPrimaryKey;
    static const std::string primaryKeyName;
    using PrimaryKeyType = std::string;
    const PrimaryKeyType &getPrimaryKey() const;

    /**
     * @brief constructor
     * @param r One row of records in the SQL query result.
     * @param indexOffset Set the offset to -1 to access all columns by column names,
     * otherwise access all columns by offsets.
     * @note If the SQL is not a style of 'select * from table_name ...' (select all
     * columns by an asterisk), please set the offset to -1.
     */
    explicit CourseVideos(const drogon::orm::Row &r, const ssize_t indexOffset = 0) noexcept;

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     */
    explicit CourseVideos(const Json::Value &pJson) noexcept(false);

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     * @param pMasqueradingVector The aliases of table columns.
     */
    CourseVideos(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false);

    CourseVideos() = default;

    void updateByJson(const Json::Value &pJson) noexcept(false);
    void updateByMasqueradedJson(const Json::Value &pJson,
                                 const std::vector<std::string> &pMasqueradingVector) noexcept(false);
    static bool validateJsonForCreation(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForCreation(const Json::Value &,
                                                const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err);
    static bool validateJsonForUpdate(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForUpdate(const Json::Value &,
                                          const std::vector<std::string> &pMasqueradingVector,
                                          std::string &err);
    static bool validJsonOfField(size_t index,
                          const std::string &fieldName,
                          const Json::Value &pJson,
                          std::string &err,
                          bool isForCreation);

    /**  For column id  */
    ///Get the value of the column id, returns the default value if the column is null
    const std::string &getValueOfId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getId() const noexcept;
    ///Set the value of the column id
    void setId(const std::string &pId) noexcept;
    void setId(std::string &&pId) noexcept;

    /**  For column course_id  */
    ///Get the value of the column course_id, returns the default value if the column is null
    const std::string &getValueOfCourseId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getCourseId() const noexcept;
    ///Set the value of the column course_id
    void setCourseId(const std::string &pCourseId) noexcept;
    void setCourseId(std::string &&pCourseId) noexcept;

    /**  For column chapter_id  */
    ///Get the value of the column chapter_id, returns the default value if the column is null
    const std::string &getValueOfChapterId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getChapterId() const noexcept;
    ///Set the value of the column chapter_id
    void setChapterId(const std::string &pChapterId) noexcept;
    void setChapterId(std::string &&pChapterId) noexcept;
    void setChapterIdToNull() noexcept;

    /**  For column author_id  */
    ///Get the value of the column author_id, returns the default value if the column is null
    const std::string &getValueOfAuthorId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getAuthorId() const noexcept;
    ///Set the value of the column author_id
    void setAuthorId(const std::string &pAuthorId) noexcept;
    void setAuthorId(std::string &&pAuthorId) noexcept;

    /**  For column title  */
    ///Get the value of the column title, returns the default value if the column is null
    const std::string &getValueOfTitle() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getTitle() const noexcept;
    ///Set the value of the column title
    void setTitle(const std::string &pTitle) noexcept;
    void setTitle(std::string &&pTitle) noexcept;

    /**  For column description  */
    ///Get the value of the column description, returns the default value if the column is null
    const std::string &getValueOfDescription() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getDescription() const noexcept;
    ///Set the value of the column description
    void setDescription(const std::string &pDescription) noexcept;
    void setDescription(std::string &&pDescription) noexcept;
    void setDescriptionToNull() noexcept;

    /**  For column order  */
    ///Get the value of the column order, returns the default value if the column is null
    const int32_t &getValueOfOrder() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getOrder() const noexcept;
    ///Set the value of the column order
    void setOrder(const int32_t &pOrder) noexcept;

    /**  For column video_filename  */
    ///Get the value of the column video_filename, returns the default value if the column is null
    const std::string &getValueOfVideoFilename() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getVideoFilename() const noexcept;
    ///Set the value of the column video_filename
    void setVideoFilename(const std::string &pVideoFilename) noexcept;
    void setVideoFilename(std::string &&pVideoFilename) noexcept;

    /**  For column video_path  */
    ///Get the value of the column video_path, returns the default value if the column is null
    const std::string &getValueOfVideoPath() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getVideoPath() const noexcept;
    ///Set the value of the column video_path
    void setVideoPath(const std::string &pVideoPath) noexcept;
    void setVideoPath(std::string &&pVideoPath) noexcept;

    /**  For column duration  */
    ///Get the value of the column duration, returns the default value if the column is null
    const std::string &getValueOfDuration() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getDuration() const noexcept;
    ///Set the value of the column duration
    void setDuration(const std::string &pDuration) noexcept;
    void setDuration(std::string &&pDuration) noexcept;
    void setDurationToNull() noexcept;

    /**  For column duration_seconds  */
    ///Get the value of the column duration_seconds, returns the default value if the column is null
    const int32_t &getValueOfDurationSeconds() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getDurationSeconds() const noexcept;
    ///Set the value of the column duration_seconds
    void setDurationSeconds(const int32_t &pDurationSeconds) noexcept;
    void setDurationSecondsToNull() noexcept;

    /**  For column cover_path  */
    ///Get the value of the column cover_path, returns the default value if the column is null
    const std::string &getValueOfCoverPath() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getCoverPath() const noexcept;
    ///Set the value of the column cover_path
    void setCoverPath(const std::string &pCoverPath) noexcept;
    void setCoverPath(std::string &&pCoverPath) noexcept;
    void setCoverPathToNull() noexcept;

    /**  For column has_subtitles  */
    ///Get the value of the column has_subtitles, returns the default value if the column is null
    const bool &getValueOfHasSubtitles() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<bool> &getHasSubtitles() const noexcept;
    ///Set the value of the column has_subtitles
    void setHasSubtitles(const bool &pHasSubtitles) noexcept;
    void setHasSubtitlesToNull() noexcept;

    /**  For column has_notes  */
    ///Get the value of the column has_notes, returns the default value if the column is null
    const bool &getValueOfHasNotes() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<bool> &getHasNotes() const noexcept;
    ///Set the value of the column has_notes
    void setHasNotes(const bool &pHasNotes) noexcept;
    void setHasNotesToNull() noexcept;

    /**  For column views_count  */
    ///Get the value of the column views_count, returns the default value if the column is null
    const int32_t &getValueOfViewsCount() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getViewsCount() const noexcept;
    ///Set the value of the column views_count
    void setViewsCount(const int32_t &pViewsCount) noexcept;
    void setViewsCountToNull() noexcept;

    /**  For column likes_count  */
    ///Get the value of the column likes_count, returns the default value if the column is null
    const int32_t &getValueOfLikesCount() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getLikesCount() const noexcept;
    ///Set the value of the column likes_count
    void setLikesCount(const int32_t &pLikesCount) noexcept;
    void setLikesCountToNull() noexcept;

    /**  For column is_approved  */
    ///Get the value of the column is_approved, returns the default value if the column is null
    const bool &getValueOfIsApproved() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<bool> &getIsApproved() const noexcept;
    ///Set the value of the column is_approved
    void setIsApproved(const bool &pIsApproved) noexcept;
    void setIsApprovedToNull() noexcept;

    /**  For column approved_by  */
    ///Get the value of the column approved_by, returns the default value if the column is null
    const std::string &getValueOfApprovedBy() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getApprovedBy() const noexcept;
    ///Set the value of the column approved_by
    void setApprovedBy(const std::string &pApprovedBy) noexcept;
    void setApprovedBy(std::string &&pApprovedBy) noexcept;
    void setApprovedByToNull() noexcept;

    /**  For column approved_at  */
    ///Get the value of the column approved_at, returns the default value if the column is null
    const ::trantor::Date &getValueOfApprovedAt() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getApprovedAt() const noexcept;
    ///Set the value of the column approved_at
    void setApprovedAt(const ::trantor::Date &pApprovedAt) noexcept;
    void setApprovedAtToNull() noexcept;

    /**  For column uploaded_by  */
    ///Get the value of the column uploaded_by, returns the default value if the column is null
    const std::string &getValueOfUploadedBy() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getUploadedBy() const noexcept;
    ///Set the value of the column uploaded_by
    void setUploadedBy(const std::string &pUploadedBy) noexcept;
    void setUploadedBy(std::string &&pUploadedBy) noexcept;
    void setUploadedByToNull() noexcept;

    /**  For column created_at  */
    ///Get the value of the column created_at, returns the default value if the column is null
    const ::trantor::Date &getValueOfCreatedAt() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getCreatedAt() const noexcept;
    ///Set the value of the column created_at
    void setCreatedAt(const ::trantor::Date &pCreatedAt) noexcept;
    void setCreatedAtToNull() noexcept;

    /**  For column updated_at  */
    ///Get the value of the column updated_at, returns the default value if the column is null
    const ::trantor::Date &getValueOfUpdatedAt() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getUpdatedAt() const noexcept;
    ///Set the value of the column updated_at
    void setUpdatedAt(const ::trantor::Date &pUpdatedAt) noexcept;
    void setUpdatedAtToNull() noexcept;

    /**  For column last_accessed_at  */
    ///Get the value of the column last_accessed_at, returns the default value if the column is null
    const ::trantor::Date &getValueOfLastAccessedAt() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getLastAccessedAt() const noexcept;
    ///Set the value of the column last_accessed_at
    void setLastAccessedAt(const ::trantor::Date &pLastAccessedAt) noexcept;
    void setLastAccessedAtToNull() noexcept;


    static size_t getColumnNumber() noexcept {  return 23;  }
    static const std::string &getColumnName(size_t index) noexcept(false);

    Json::Value toJson() const;
    std::string toString() const;
    Json::Value toMasqueradedJson(const std::vector<std::string> &pMasqueradingVector) const;
    /// Relationship interfaces
  private:
    friend drogon::orm::Mapper<CourseVideos>;
    friend drogon::orm::BaseBuilder<CourseVideos, true, true>;
    friend drogon::orm::BaseBuilder<CourseVideos, true, false>;
    friend drogon::orm::BaseBuilder<CourseVideos, false, true>;
    friend drogon::orm::BaseBuilder<CourseVideos, false, false>;
#ifdef __cpp_impl_coroutine
    friend drogon::orm::CoroMapper<CourseVideos>;
#endif
    static const std::vector<std::string> &insertColumns() noexcept;
    void outputArgs(drogon::orm::internal::SqlBinder &binder) const;
    const std::vector<std::string> updateColumns() const;
    void updateArgs(drogon::orm::internal::SqlBinder &binder) const;
    ///For mysql or sqlite3
    void updateId(const uint64_t id);
    std::shared_ptr<std::string> id_;
    std::shared_ptr<std::string> courseId_;
    std::shared_ptr<std::string> chapterId_;
    std::shared_ptr<std::string> authorId_;
    std::shared_ptr<std::string> title_;
    std::shared_ptr<std::string> description_;
    std::shared_ptr<int32_t> order_;
    std::shared_ptr<std::string> videoFilename_;
    std::shared_ptr<std::string> videoPath_;
    std::shared_ptr<std::string> duration_;
    std::shared_ptr<int32_t> durationSeconds_;
    std::shared_ptr<std::string> coverPath_;
    std::shared_ptr<bool> hasSubtitles_;
    std::shared_ptr<bool> hasNotes_;
    std::shared_ptr<int32_t> viewsCount_;
    std::shared_ptr<int32_t> likesCount_;
    std::shared_ptr<bool> isApproved_;
    std::shared_ptr<std::string> approvedBy_;
    std::shared_ptr<::trantor::Date> approvedAt_;
    std::shared_ptr<std::string> uploadedBy_;
    std::shared_ptr<::trantor::Date> createdAt_;
    std::shared_ptr<::trantor::Date> updatedAt_;
    std::shared_ptr<::trantor::Date> lastAccessedAt_;
    struct MetaData
    {
        const std::string colName_;
        const std::string colType_;
        const std::string colDatabaseType_;
        const ssize_t colLength_;
        const bool isAutoVal_;
        const bool isPrimaryKey_;
        const bool notNull_;
    };
    static const std::vector<MetaData> metaData_;
    bool dirtyFlag_[23]={ false };
  public:
    static const std::string &sqlForFindingByPrimaryKey()
    {
        static const std::string sql="select * from " + tableName + " where id = $1";
        return sql;
    }

    static const std::string &sqlForDeletingByPrimaryKey()
    {
        static const std::string sql="delete from " + tableName + " where id = $1";
        return sql;
    }
    std::string sqlForInserting(bool &needSelection) const
    {
        std::string sql="insert into " + tableName + " (";
        size_t parametersCount = 0;
        needSelection = false;
        sql += "id,";
        ++parametersCount;
        if(!dirtyFlag_[0])
        {
            needSelection=true;
        }
        if(dirtyFlag_[1])
        {
            sql += "course_id,";
            ++parametersCount;
        }
        if(dirtyFlag_[2])
        {
            sql += "chapter_id,";
            ++parametersCount;
        }
        if(dirtyFlag_[3])
        {
            sql += "author_id,";
            ++parametersCount;
        }
        if(dirtyFlag_[4])
        {
            sql += "title,";
            ++parametersCount;
        }
        if(dirtyFlag_[5])
        {
            sql += "description,";
            ++parametersCount;
        }
        if(dirtyFlag_[6])
        {
            sql += "order,";
            ++parametersCount;
        }
        if(dirtyFlag_[7])
        {
            sql += "video_filename,";
            ++parametersCount;
        }
        if(dirtyFlag_[8])
        {
            sql += "video_path,";
            ++parametersCount;
        }
        if(dirtyFlag_[9])
        {
            sql += "duration,";
            ++parametersCount;
        }
        if(dirtyFlag_[10])
        {
            sql += "duration_seconds,";
            ++parametersCount;
        }
        if(dirtyFlag_[11])
        {
            sql += "cover_path,";
            ++parametersCount;
        }
        sql += "has_subtitles,";
        ++parametersCount;
        if(!dirtyFlag_[12])
        {
            needSelection=true;
        }
        sql += "has_notes,";
        ++parametersCount;
        if(!dirtyFlag_[13])
        {
            needSelection=true;
        }
        sql += "views_count,";
        ++parametersCount;
        if(!dirtyFlag_[14])
        {
            needSelection=true;
        }
        sql += "likes_count,";
        ++parametersCount;
        if(!dirtyFlag_[15])
        {
            needSelection=true;
        }
        sql += "is_approved,";
        ++parametersCount;
        if(!dirtyFlag_[16])
        {
            needSelection=true;
        }
        if(dirtyFlag_[17])
        {
            sql += "approved_by,";
            ++parametersCount;
        }
        if(dirtyFlag_[18])
        {
            sql += "approved_at,";
            ++parametersCount;
        }
        if(dirtyFlag_[19])
        {
            sql += "uploaded_by,";
            ++parametersCount;
        }
        sql += "created_at,";
        ++parametersCount;
        if(!dirtyFlag_[20])
        {
            needSelection=true;
        }
        sql += "updated_at,";
        ++parametersCount;
        if(!dirtyFlag_[21])
        {
            needSelection=true;
        }
        sql += "last_accessed_at,";
        ++parametersCount;
        if(!dirtyFlag_[22])
        {
            needSelection=true;
        }
        if(parametersCount > 0)
        {
            sql[sql.length()-1]=')';
            sql += " values (";
        }
        else
            sql += ") values (";

        int placeholder=1;
        char placeholderStr[64];
        size_t n=0;
        if(dirtyFlag_[0])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[1])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[2])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[3])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[4])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[5])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[6])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[7])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[8])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[9])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[10])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[11])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[12])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[13])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[14])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[15])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[16])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[17])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[18])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[19])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[20])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[21])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[22])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(parametersCount > 0)
        {
            sql.resize(sql.length() - 1);
        }
        if(needSelection)
        {
            sql.append(") returning *");
        }
        else
        {
            sql.append(1, ')');
        }
        LOG_TRACE << sql;
        return sql;
    }
};
} // namespace myserver
} // namespace drogon_model
