/**
 *
 *  UserProgress.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "UserProgress.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::myserver;

const std::string UserProgress::Cols::_id = "\"id\"";
const std::string UserProgress::Cols::_user_id = "\"user_id\"";
const std::string UserProgress::Cols::_course_id = "\"course_id\"";
const std::string UserProgress::Cols::_chapter_id = "\"chapter_id\"";
const std::string UserProgress::Cols::_video_id = "\"video_id\"";
const std::string UserProgress::Cols::_completed = "\"completed\"";
const std::string UserProgress::Cols::_watched_seconds = "\"watched_seconds\"";
const std::string UserProgress::Cols::_total_seconds = "\"total_seconds\"";
const std::string UserProgress::Cols::_progress_percentage = "\"progress_percentage\"";
const std::string UserProgress::Cols::_last_watched_at = "\"last_watched_at\"";
const std::string UserProgress::Cols::_completed_at = "\"completed_at\"";
const std::string UserProgress::Cols::_created_at = "\"created_at\"";
const std::string UserProgress::Cols::_updated_at = "\"updated_at\"";
const std::string UserProgress::primaryKeyName = "id";
const bool UserProgress::hasPrimaryKey = true;
const std::string UserProgress::tableName = "\"user_progress\"";

const std::vector<typename UserProgress::MetaData> UserProgress::metaData_={
{"id","std::string","text",0,0,1,1},
{"user_id","std::string","text",0,0,0,1},
{"course_id","std::string","text",0,0,0,0},
{"chapter_id","std::string","text",0,0,0,0},
{"video_id","std::string","text",0,0,0,0},
{"completed","bool","boolean",1,0,0,0},
{"watched_seconds","int32_t","integer",4,0,0,0},
{"total_seconds","int32_t","integer",4,0,0,0},
{"progress_percentage","int32_t","integer",4,0,0,0},
{"last_watched_at","::trantor::Date","timestamp with time zone",0,0,0,0},
{"completed_at","::trantor::Date","timestamp with time zone",0,0,0,0},
{"created_at","::trantor::Date","timestamp with time zone",0,0,0,0},
{"updated_at","::trantor::Date","timestamp with time zone",0,0,0,0}
};
const std::string &UserProgress::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
UserProgress::UserProgress(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<std::string>(r["id"].as<std::string>());
        }
        if(!r["user_id"].isNull())
        {
            userId_=std::make_shared<std::string>(r["user_id"].as<std::string>());
        }
        if(!r["course_id"].isNull())
        {
            courseId_=std::make_shared<std::string>(r["course_id"].as<std::string>());
        }
        if(!r["chapter_id"].isNull())
        {
            chapterId_=std::make_shared<std::string>(r["chapter_id"].as<std::string>());
        }
        if(!r["video_id"].isNull())
        {
            videoId_=std::make_shared<std::string>(r["video_id"].as<std::string>());
        }
        if(!r["completed"].isNull())
        {
            completed_=std::make_shared<bool>(r["completed"].as<bool>());
        }
        if(!r["watched_seconds"].isNull())
        {
            watchedSeconds_=std::make_shared<int32_t>(r["watched_seconds"].as<int32_t>());
        }
        if(!r["total_seconds"].isNull())
        {
            totalSeconds_=std::make_shared<int32_t>(r["total_seconds"].as<int32_t>());
        }
        if(!r["progress_percentage"].isNull())
        {
            progressPercentage_=std::make_shared<int32_t>(r["progress_percentage"].as<int32_t>());
        }
        if(!r["last_watched_at"].isNull())
        {
            auto timeStr = r["last_watched_at"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                lastWatchedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        if(!r["completed_at"].isNull())
        {
            auto timeStr = r["completed_at"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                completedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        if(!r["created_at"].isNull())
        {
            auto timeStr = r["created_at"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        if(!r["updated_at"].isNull())
        {
            auto timeStr = r["updated_at"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                updatedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 13 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            userId_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            courseId_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            chapterId_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            videoId_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 5;
        if(!r[index].isNull())
        {
            completed_=std::make_shared<bool>(r[index].as<bool>());
        }
        index = offset + 6;
        if(!r[index].isNull())
        {
            watchedSeconds_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 7;
        if(!r[index].isNull())
        {
            totalSeconds_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 8;
        if(!r[index].isNull())
        {
            progressPercentage_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 9;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                lastWatchedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        index = offset + 10;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                completedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        index = offset + 11;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        index = offset + 12;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                updatedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }

}

UserProgress::UserProgress(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 13)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            userId_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            courseId_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            chapterId_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            videoId_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            completed_=std::make_shared<bool>(pJson[pMasqueradingVector[5]].asBool());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            watchedSeconds_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[6]].asInt64());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            totalSeconds_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[7]].asInt64());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            progressPercentage_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[8]].asInt64());
        }
    }
    if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
    {
        dirtyFlag_[9] = true;
        if(!pJson[pMasqueradingVector[9]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[9]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                lastWatchedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
    {
        dirtyFlag_[10] = true;
        if(!pJson[pMasqueradingVector[10]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[10]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                completedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11]))
    {
        dirtyFlag_[11] = true;
        if(!pJson[pMasqueradingVector[11]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[11]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[12].empty() && pJson.isMember(pMasqueradingVector[12]))
    {
        dirtyFlag_[12] = true;
        if(!pJson[pMasqueradingVector[12]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[12]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                updatedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

UserProgress::UserProgress(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<std::string>(pJson["id"].asString());
        }
    }
    if(pJson.isMember("user_id"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["user_id"].isNull())
        {
            userId_=std::make_shared<std::string>(pJson["user_id"].asString());
        }
    }
    if(pJson.isMember("course_id"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["course_id"].isNull())
        {
            courseId_=std::make_shared<std::string>(pJson["course_id"].asString());
        }
    }
    if(pJson.isMember("chapter_id"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["chapter_id"].isNull())
        {
            chapterId_=std::make_shared<std::string>(pJson["chapter_id"].asString());
        }
    }
    if(pJson.isMember("video_id"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["video_id"].isNull())
        {
            videoId_=std::make_shared<std::string>(pJson["video_id"].asString());
        }
    }
    if(pJson.isMember("completed"))
    {
        dirtyFlag_[5]=true;
        if(!pJson["completed"].isNull())
        {
            completed_=std::make_shared<bool>(pJson["completed"].asBool());
        }
    }
    if(pJson.isMember("watched_seconds"))
    {
        dirtyFlag_[6]=true;
        if(!pJson["watched_seconds"].isNull())
        {
            watchedSeconds_=std::make_shared<int32_t>((int32_t)pJson["watched_seconds"].asInt64());
        }
    }
    if(pJson.isMember("total_seconds"))
    {
        dirtyFlag_[7]=true;
        if(!pJson["total_seconds"].isNull())
        {
            totalSeconds_=std::make_shared<int32_t>((int32_t)pJson["total_seconds"].asInt64());
        }
    }
    if(pJson.isMember("progress_percentage"))
    {
        dirtyFlag_[8]=true;
        if(!pJson["progress_percentage"].isNull())
        {
            progressPercentage_=std::make_shared<int32_t>((int32_t)pJson["progress_percentage"].asInt64());
        }
    }
    if(pJson.isMember("last_watched_at"))
    {
        dirtyFlag_[9]=true;
        if(!pJson["last_watched_at"].isNull())
        {
            auto timeStr = pJson["last_watched_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                lastWatchedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("completed_at"))
    {
        dirtyFlag_[10]=true;
        if(!pJson["completed_at"].isNull())
        {
            auto timeStr = pJson["completed_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                completedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("created_at"))
    {
        dirtyFlag_[11]=true;
        if(!pJson["created_at"].isNull())
        {
            auto timeStr = pJson["created_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("updated_at"))
    {
        dirtyFlag_[12]=true;
        if(!pJson["updated_at"].isNull())
        {
            auto timeStr = pJson["updated_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                updatedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

void UserProgress::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 13)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            userId_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            courseId_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            chapterId_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            videoId_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            completed_=std::make_shared<bool>(pJson[pMasqueradingVector[5]].asBool());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            watchedSeconds_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[6]].asInt64());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            totalSeconds_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[7]].asInt64());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            progressPercentage_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[8]].asInt64());
        }
    }
    if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
    {
        dirtyFlag_[9] = true;
        if(!pJson[pMasqueradingVector[9]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[9]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                lastWatchedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
    {
        dirtyFlag_[10] = true;
        if(!pJson[pMasqueradingVector[10]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[10]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                completedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11]))
    {
        dirtyFlag_[11] = true;
        if(!pJson[pMasqueradingVector[11]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[11]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[12].empty() && pJson.isMember(pMasqueradingVector[12]))
    {
        dirtyFlag_[12] = true;
        if(!pJson[pMasqueradingVector[12]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[12]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                updatedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

void UserProgress::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<std::string>(pJson["id"].asString());
        }
    }
    if(pJson.isMember("user_id"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["user_id"].isNull())
        {
            userId_=std::make_shared<std::string>(pJson["user_id"].asString());
        }
    }
    if(pJson.isMember("course_id"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["course_id"].isNull())
        {
            courseId_=std::make_shared<std::string>(pJson["course_id"].asString());
        }
    }
    if(pJson.isMember("chapter_id"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["chapter_id"].isNull())
        {
            chapterId_=std::make_shared<std::string>(pJson["chapter_id"].asString());
        }
    }
    if(pJson.isMember("video_id"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["video_id"].isNull())
        {
            videoId_=std::make_shared<std::string>(pJson["video_id"].asString());
        }
    }
    if(pJson.isMember("completed"))
    {
        dirtyFlag_[5] = true;
        if(!pJson["completed"].isNull())
        {
            completed_=std::make_shared<bool>(pJson["completed"].asBool());
        }
    }
    if(pJson.isMember("watched_seconds"))
    {
        dirtyFlag_[6] = true;
        if(!pJson["watched_seconds"].isNull())
        {
            watchedSeconds_=std::make_shared<int32_t>((int32_t)pJson["watched_seconds"].asInt64());
        }
    }
    if(pJson.isMember("total_seconds"))
    {
        dirtyFlag_[7] = true;
        if(!pJson["total_seconds"].isNull())
        {
            totalSeconds_=std::make_shared<int32_t>((int32_t)pJson["total_seconds"].asInt64());
        }
    }
    if(pJson.isMember("progress_percentage"))
    {
        dirtyFlag_[8] = true;
        if(!pJson["progress_percentage"].isNull())
        {
            progressPercentage_=std::make_shared<int32_t>((int32_t)pJson["progress_percentage"].asInt64());
        }
    }
    if(pJson.isMember("last_watched_at"))
    {
        dirtyFlag_[9] = true;
        if(!pJson["last_watched_at"].isNull())
        {
            auto timeStr = pJson["last_watched_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                lastWatchedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("completed_at"))
    {
        dirtyFlag_[10] = true;
        if(!pJson["completed_at"].isNull())
        {
            auto timeStr = pJson["completed_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                completedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("created_at"))
    {
        dirtyFlag_[11] = true;
        if(!pJson["created_at"].isNull())
        {
            auto timeStr = pJson["created_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("updated_at"))
    {
        dirtyFlag_[12] = true;
        if(!pJson["updated_at"].isNull())
        {
            auto timeStr = pJson["updated_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                updatedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

const std::string &UserProgress::getValueOfId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<std::string> &UserProgress::getId() const noexcept
{
    return id_;
}
void UserProgress::setId(const std::string &pId) noexcept
{
    id_ = std::make_shared<std::string>(pId);
    dirtyFlag_[0] = true;
}
void UserProgress::setId(std::string &&pId) noexcept
{
    id_ = std::make_shared<std::string>(std::move(pId));
    dirtyFlag_[0] = true;
}
const typename UserProgress::PrimaryKeyType & UserProgress::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const std::string &UserProgress::getValueOfUserId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(userId_)
        return *userId_;
    return defaultValue;
}
const std::shared_ptr<std::string> &UserProgress::getUserId() const noexcept
{
    return userId_;
}
void UserProgress::setUserId(const std::string &pUserId) noexcept
{
    userId_ = std::make_shared<std::string>(pUserId);
    dirtyFlag_[1] = true;
}
void UserProgress::setUserId(std::string &&pUserId) noexcept
{
    userId_ = std::make_shared<std::string>(std::move(pUserId));
    dirtyFlag_[1] = true;
}

const std::string &UserProgress::getValueOfCourseId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(courseId_)
        return *courseId_;
    return defaultValue;
}
const std::shared_ptr<std::string> &UserProgress::getCourseId() const noexcept
{
    return courseId_;
}
void UserProgress::setCourseId(const std::string &pCourseId) noexcept
{
    courseId_ = std::make_shared<std::string>(pCourseId);
    dirtyFlag_[2] = true;
}
void UserProgress::setCourseId(std::string &&pCourseId) noexcept
{
    courseId_ = std::make_shared<std::string>(std::move(pCourseId));
    dirtyFlag_[2] = true;
}
void UserProgress::setCourseIdToNull() noexcept
{
    courseId_.reset();
    dirtyFlag_[2] = true;
}

const std::string &UserProgress::getValueOfChapterId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(chapterId_)
        return *chapterId_;
    return defaultValue;
}
const std::shared_ptr<std::string> &UserProgress::getChapterId() const noexcept
{
    return chapterId_;
}
void UserProgress::setChapterId(const std::string &pChapterId) noexcept
{
    chapterId_ = std::make_shared<std::string>(pChapterId);
    dirtyFlag_[3] = true;
}
void UserProgress::setChapterId(std::string &&pChapterId) noexcept
{
    chapterId_ = std::make_shared<std::string>(std::move(pChapterId));
    dirtyFlag_[3] = true;
}
void UserProgress::setChapterIdToNull() noexcept
{
    chapterId_.reset();
    dirtyFlag_[3] = true;
}

const std::string &UserProgress::getValueOfVideoId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(videoId_)
        return *videoId_;
    return defaultValue;
}
const std::shared_ptr<std::string> &UserProgress::getVideoId() const noexcept
{
    return videoId_;
}
void UserProgress::setVideoId(const std::string &pVideoId) noexcept
{
    videoId_ = std::make_shared<std::string>(pVideoId);
    dirtyFlag_[4] = true;
}
void UserProgress::setVideoId(std::string &&pVideoId) noexcept
{
    videoId_ = std::make_shared<std::string>(std::move(pVideoId));
    dirtyFlag_[4] = true;
}
void UserProgress::setVideoIdToNull() noexcept
{
    videoId_.reset();
    dirtyFlag_[4] = true;
}

const bool &UserProgress::getValueOfCompleted() const noexcept
{
    static const bool defaultValue = bool();
    if(completed_)
        return *completed_;
    return defaultValue;
}
const std::shared_ptr<bool> &UserProgress::getCompleted() const noexcept
{
    return completed_;
}
void UserProgress::setCompleted(const bool &pCompleted) noexcept
{
    completed_ = std::make_shared<bool>(pCompleted);
    dirtyFlag_[5] = true;
}
void UserProgress::setCompletedToNull() noexcept
{
    completed_.reset();
    dirtyFlag_[5] = true;
}

const int32_t &UserProgress::getValueOfWatchedSeconds() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(watchedSeconds_)
        return *watchedSeconds_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &UserProgress::getWatchedSeconds() const noexcept
{
    return watchedSeconds_;
}
void UserProgress::setWatchedSeconds(const int32_t &pWatchedSeconds) noexcept
{
    watchedSeconds_ = std::make_shared<int32_t>(pWatchedSeconds);
    dirtyFlag_[6] = true;
}
void UserProgress::setWatchedSecondsToNull() noexcept
{
    watchedSeconds_.reset();
    dirtyFlag_[6] = true;
}

const int32_t &UserProgress::getValueOfTotalSeconds() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(totalSeconds_)
        return *totalSeconds_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &UserProgress::getTotalSeconds() const noexcept
{
    return totalSeconds_;
}
void UserProgress::setTotalSeconds(const int32_t &pTotalSeconds) noexcept
{
    totalSeconds_ = std::make_shared<int32_t>(pTotalSeconds);
    dirtyFlag_[7] = true;
}
void UserProgress::setTotalSecondsToNull() noexcept
{
    totalSeconds_.reset();
    dirtyFlag_[7] = true;
}

const int32_t &UserProgress::getValueOfProgressPercentage() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(progressPercentage_)
        return *progressPercentage_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &UserProgress::getProgressPercentage() const noexcept
{
    return progressPercentage_;
}
void UserProgress::setProgressPercentage(const int32_t &pProgressPercentage) noexcept
{
    progressPercentage_ = std::make_shared<int32_t>(pProgressPercentage);
    dirtyFlag_[8] = true;
}
void UserProgress::setProgressPercentageToNull() noexcept
{
    progressPercentage_.reset();
    dirtyFlag_[8] = true;
}

const ::trantor::Date &UserProgress::getValueOfLastWatchedAt() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(lastWatchedAt_)
        return *lastWatchedAt_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &UserProgress::getLastWatchedAt() const noexcept
{
    return lastWatchedAt_;
}
void UserProgress::setLastWatchedAt(const ::trantor::Date &pLastWatchedAt) noexcept
{
    lastWatchedAt_ = std::make_shared<::trantor::Date>(pLastWatchedAt);
    dirtyFlag_[9] = true;
}
void UserProgress::setLastWatchedAtToNull() noexcept
{
    lastWatchedAt_.reset();
    dirtyFlag_[9] = true;
}

const ::trantor::Date &UserProgress::getValueOfCompletedAt() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(completedAt_)
        return *completedAt_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &UserProgress::getCompletedAt() const noexcept
{
    return completedAt_;
}
void UserProgress::setCompletedAt(const ::trantor::Date &pCompletedAt) noexcept
{
    completedAt_ = std::make_shared<::trantor::Date>(pCompletedAt);
    dirtyFlag_[10] = true;
}
void UserProgress::setCompletedAtToNull() noexcept
{
    completedAt_.reset();
    dirtyFlag_[10] = true;
}

const ::trantor::Date &UserProgress::getValueOfCreatedAt() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(createdAt_)
        return *createdAt_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &UserProgress::getCreatedAt() const noexcept
{
    return createdAt_;
}
void UserProgress::setCreatedAt(const ::trantor::Date &pCreatedAt) noexcept
{
    createdAt_ = std::make_shared<::trantor::Date>(pCreatedAt);
    dirtyFlag_[11] = true;
}
void UserProgress::setCreatedAtToNull() noexcept
{
    createdAt_.reset();
    dirtyFlag_[11] = true;
}

const ::trantor::Date &UserProgress::getValueOfUpdatedAt() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(updatedAt_)
        return *updatedAt_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &UserProgress::getUpdatedAt() const noexcept
{
    return updatedAt_;
}
void UserProgress::setUpdatedAt(const ::trantor::Date &pUpdatedAt) noexcept
{
    updatedAt_ = std::make_shared<::trantor::Date>(pUpdatedAt);
    dirtyFlag_[12] = true;
}
void UserProgress::setUpdatedAtToNull() noexcept
{
    updatedAt_.reset();
    dirtyFlag_[12] = true;
}

void UserProgress::updateId(const uint64_t id)
{
}

const std::vector<std::string> &UserProgress::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "id",
        "user_id",
        "course_id",
        "chapter_id",
        "video_id",
        "completed",
        "watched_seconds",
        "total_seconds",
        "progress_percentage",
        "last_watched_at",
        "completed_at",
        "created_at",
        "updated_at"
    };
    return inCols;
}

void UserProgress::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getId())
        {
            binder << getValueOfId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getUserId())
        {
            binder << getValueOfUserId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getCourseId())
        {
            binder << getValueOfCourseId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getChapterId())
        {
            binder << getValueOfChapterId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getVideoId())
        {
            binder << getValueOfVideoId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getCompleted())
        {
            binder << getValueOfCompleted();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getWatchedSeconds())
        {
            binder << getValueOfWatchedSeconds();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getTotalSeconds())
        {
            binder << getValueOfTotalSeconds();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getProgressPercentage())
        {
            binder << getValueOfProgressPercentage();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[9])
    {
        if(getLastWatchedAt())
        {
            binder << getValueOfLastWatchedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[10])
    {
        if(getCompletedAt())
        {
            binder << getValueOfCompletedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[11])
    {
        if(getCreatedAt())
        {
            binder << getValueOfCreatedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[12])
    {
        if(getUpdatedAt())
        {
            binder << getValueOfUpdatedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> UserProgress::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[0])
    {
        ret.push_back(getColumnName(0));
    }
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if(dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    if(dirtyFlag_[6])
    {
        ret.push_back(getColumnName(6));
    }
    if(dirtyFlag_[7])
    {
        ret.push_back(getColumnName(7));
    }
    if(dirtyFlag_[8])
    {
        ret.push_back(getColumnName(8));
    }
    if(dirtyFlag_[9])
    {
        ret.push_back(getColumnName(9));
    }
    if(dirtyFlag_[10])
    {
        ret.push_back(getColumnName(10));
    }
    if(dirtyFlag_[11])
    {
        ret.push_back(getColumnName(11));
    }
    if(dirtyFlag_[12])
    {
        ret.push_back(getColumnName(12));
    }
    return ret;
}

void UserProgress::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getId())
        {
            binder << getValueOfId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getUserId())
        {
            binder << getValueOfUserId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getCourseId())
        {
            binder << getValueOfCourseId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getChapterId())
        {
            binder << getValueOfChapterId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getVideoId())
        {
            binder << getValueOfVideoId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getCompleted())
        {
            binder << getValueOfCompleted();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getWatchedSeconds())
        {
            binder << getValueOfWatchedSeconds();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getTotalSeconds())
        {
            binder << getValueOfTotalSeconds();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getProgressPercentage())
        {
            binder << getValueOfProgressPercentage();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[9])
    {
        if(getLastWatchedAt())
        {
            binder << getValueOfLastWatchedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[10])
    {
        if(getCompletedAt())
        {
            binder << getValueOfCompletedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[11])
    {
        if(getCreatedAt())
        {
            binder << getValueOfCreatedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[12])
    {
        if(getUpdatedAt())
        {
            binder << getValueOfUpdatedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value UserProgress::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getUserId())
    {
        ret["user_id"]=getValueOfUserId();
    }
    else
    {
        ret["user_id"]=Json::Value();
    }
    if(getCourseId())
    {
        ret["course_id"]=getValueOfCourseId();
    }
    else
    {
        ret["course_id"]=Json::Value();
    }
    if(getChapterId())
    {
        ret["chapter_id"]=getValueOfChapterId();
    }
    else
    {
        ret["chapter_id"]=Json::Value();
    }
    if(getVideoId())
    {
        ret["video_id"]=getValueOfVideoId();
    }
    else
    {
        ret["video_id"]=Json::Value();
    }
    if(getCompleted())
    {
        ret["completed"]=getValueOfCompleted();
    }
    else
    {
        ret["completed"]=Json::Value();
    }
    if(getWatchedSeconds())
    {
        ret["watched_seconds"]=getValueOfWatchedSeconds();
    }
    else
    {
        ret["watched_seconds"]=Json::Value();
    }
    if(getTotalSeconds())
    {
        ret["total_seconds"]=getValueOfTotalSeconds();
    }
    else
    {
        ret["total_seconds"]=Json::Value();
    }
    if(getProgressPercentage())
    {
        ret["progress_percentage"]=getValueOfProgressPercentage();
    }
    else
    {
        ret["progress_percentage"]=Json::Value();
    }
    if(getLastWatchedAt())
    {
        ret["last_watched_at"]=getLastWatchedAt()->toDbStringLocal();
    }
    else
    {
        ret["last_watched_at"]=Json::Value();
    }
    if(getCompletedAt())
    {
        ret["completed_at"]=getCompletedAt()->toDbStringLocal();
    }
    else
    {
        ret["completed_at"]=Json::Value();
    }
    if(getCreatedAt())
    {
        ret["created_at"]=getCreatedAt()->toDbStringLocal();
    }
    else
    {
        ret["created_at"]=Json::Value();
    }
    if(getUpdatedAt())
    {
        ret["updated_at"]=getUpdatedAt()->toDbStringLocal();
    }
    else
    {
        ret["updated_at"]=Json::Value();
    }
    return ret;
}

std::string UserProgress::toString() const
{
    return toJson().toStyledString();
}

Json::Value UserProgress::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 13)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getUserId())
            {
                ret[pMasqueradingVector[1]]=getValueOfUserId();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getCourseId())
            {
                ret[pMasqueradingVector[2]]=getValueOfCourseId();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getChapterId())
            {
                ret[pMasqueradingVector[3]]=getValueOfChapterId();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getVideoId())
            {
                ret[pMasqueradingVector[4]]=getValueOfVideoId();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[5].empty())
        {
            if(getCompleted())
            {
                ret[pMasqueradingVector[5]]=getValueOfCompleted();
            }
            else
            {
                ret[pMasqueradingVector[5]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[6].empty())
        {
            if(getWatchedSeconds())
            {
                ret[pMasqueradingVector[6]]=getValueOfWatchedSeconds();
            }
            else
            {
                ret[pMasqueradingVector[6]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[7].empty())
        {
            if(getTotalSeconds())
            {
                ret[pMasqueradingVector[7]]=getValueOfTotalSeconds();
            }
            else
            {
                ret[pMasqueradingVector[7]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[8].empty())
        {
            if(getProgressPercentage())
            {
                ret[pMasqueradingVector[8]]=getValueOfProgressPercentage();
            }
            else
            {
                ret[pMasqueradingVector[8]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[9].empty())
        {
            if(getLastWatchedAt())
            {
                ret[pMasqueradingVector[9]]=getLastWatchedAt()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[9]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[10].empty())
        {
            if(getCompletedAt())
            {
                ret[pMasqueradingVector[10]]=getCompletedAt()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[10]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[11].empty())
        {
            if(getCreatedAt())
            {
                ret[pMasqueradingVector[11]]=getCreatedAt()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[11]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[12].empty())
        {
            if(getUpdatedAt())
            {
                ret[pMasqueradingVector[12]]=getUpdatedAt()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[12]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getUserId())
    {
        ret["user_id"]=getValueOfUserId();
    }
    else
    {
        ret["user_id"]=Json::Value();
    }
    if(getCourseId())
    {
        ret["course_id"]=getValueOfCourseId();
    }
    else
    {
        ret["course_id"]=Json::Value();
    }
    if(getChapterId())
    {
        ret["chapter_id"]=getValueOfChapterId();
    }
    else
    {
        ret["chapter_id"]=Json::Value();
    }
    if(getVideoId())
    {
        ret["video_id"]=getValueOfVideoId();
    }
    else
    {
        ret["video_id"]=Json::Value();
    }
    if(getCompleted())
    {
        ret["completed"]=getValueOfCompleted();
    }
    else
    {
        ret["completed"]=Json::Value();
    }
    if(getWatchedSeconds())
    {
        ret["watched_seconds"]=getValueOfWatchedSeconds();
    }
    else
    {
        ret["watched_seconds"]=Json::Value();
    }
    if(getTotalSeconds())
    {
        ret["total_seconds"]=getValueOfTotalSeconds();
    }
    else
    {
        ret["total_seconds"]=Json::Value();
    }
    if(getProgressPercentage())
    {
        ret["progress_percentage"]=getValueOfProgressPercentage();
    }
    else
    {
        ret["progress_percentage"]=Json::Value();
    }
    if(getLastWatchedAt())
    {
        ret["last_watched_at"]=getLastWatchedAt()->toDbStringLocal();
    }
    else
    {
        ret["last_watched_at"]=Json::Value();
    }
    if(getCompletedAt())
    {
        ret["completed_at"]=getCompletedAt()->toDbStringLocal();
    }
    else
    {
        ret["completed_at"]=Json::Value();
    }
    if(getCreatedAt())
    {
        ret["created_at"]=getCreatedAt()->toDbStringLocal();
    }
    else
    {
        ret["created_at"]=Json::Value();
    }
    if(getUpdatedAt())
    {
        ret["updated_at"]=getUpdatedAt()->toDbStringLocal();
    }
    else
    {
        ret["updated_at"]=Json::Value();
    }
    return ret;
}

bool UserProgress::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    if(pJson.isMember("user_id"))
    {
        if(!validJsonOfField(1, "user_id", pJson["user_id"], err, true))
            return false;
    }
    else
    {
        err="The user_id column cannot be null";
        return false;
    }
    if(pJson.isMember("course_id"))
    {
        if(!validJsonOfField(2, "course_id", pJson["course_id"], err, true))
            return false;
    }
    if(pJson.isMember("chapter_id"))
    {
        if(!validJsonOfField(3, "chapter_id", pJson["chapter_id"], err, true))
            return false;
    }
    if(pJson.isMember("video_id"))
    {
        if(!validJsonOfField(4, "video_id", pJson["video_id"], err, true))
            return false;
    }
    if(pJson.isMember("completed"))
    {
        if(!validJsonOfField(5, "completed", pJson["completed"], err, true))
            return false;
    }
    if(pJson.isMember("watched_seconds"))
    {
        if(!validJsonOfField(6, "watched_seconds", pJson["watched_seconds"], err, true))
            return false;
    }
    if(pJson.isMember("total_seconds"))
    {
        if(!validJsonOfField(7, "total_seconds", pJson["total_seconds"], err, true))
            return false;
    }
    if(pJson.isMember("progress_percentage"))
    {
        if(!validJsonOfField(8, "progress_percentage", pJson["progress_percentage"], err, true))
            return false;
    }
    if(pJson.isMember("last_watched_at"))
    {
        if(!validJsonOfField(9, "last_watched_at", pJson["last_watched_at"], err, true))
            return false;
    }
    if(pJson.isMember("completed_at"))
    {
        if(!validJsonOfField(10, "completed_at", pJson["completed_at"], err, true))
            return false;
    }
    if(pJson.isMember("created_at"))
    {
        if(!validJsonOfField(11, "created_at", pJson["created_at"], err, true))
            return false;
    }
    if(pJson.isMember("updated_at"))
    {
        if(!validJsonOfField(12, "updated_at", pJson["updated_at"], err, true))
            return false;
    }
    return true;
}
bool UserProgress::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                      const std::vector<std::string> &pMasqueradingVector,
                                                      std::string &err)
{
    if(pMasqueradingVector.size() != 13)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[5].empty())
      {
          if(pJson.isMember(pMasqueradingVector[5]))
          {
              if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[6].empty())
      {
          if(pJson.isMember(pMasqueradingVector[6]))
          {
              if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[7].empty())
      {
          if(pJson.isMember(pMasqueradingVector[7]))
          {
              if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[8].empty())
      {
          if(pJson.isMember(pMasqueradingVector[8]))
          {
              if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[9].empty())
      {
          if(pJson.isMember(pMasqueradingVector[9]))
          {
              if(!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[10].empty())
      {
          if(pJson.isMember(pMasqueradingVector[10]))
          {
              if(!validJsonOfField(10, pMasqueradingVector[10], pJson[pMasqueradingVector[10]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[11].empty())
      {
          if(pJson.isMember(pMasqueradingVector[11]))
          {
              if(!validJsonOfField(11, pMasqueradingVector[11], pJson[pMasqueradingVector[11]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[12].empty())
      {
          if(pJson.isMember(pMasqueradingVector[12]))
          {
              if(!validJsonOfField(12, pMasqueradingVector[12], pJson[pMasqueradingVector[12]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool UserProgress::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("user_id"))
    {
        if(!validJsonOfField(1, "user_id", pJson["user_id"], err, false))
            return false;
    }
    if(pJson.isMember("course_id"))
    {
        if(!validJsonOfField(2, "course_id", pJson["course_id"], err, false))
            return false;
    }
    if(pJson.isMember("chapter_id"))
    {
        if(!validJsonOfField(3, "chapter_id", pJson["chapter_id"], err, false))
            return false;
    }
    if(pJson.isMember("video_id"))
    {
        if(!validJsonOfField(4, "video_id", pJson["video_id"], err, false))
            return false;
    }
    if(pJson.isMember("completed"))
    {
        if(!validJsonOfField(5, "completed", pJson["completed"], err, false))
            return false;
    }
    if(pJson.isMember("watched_seconds"))
    {
        if(!validJsonOfField(6, "watched_seconds", pJson["watched_seconds"], err, false))
            return false;
    }
    if(pJson.isMember("total_seconds"))
    {
        if(!validJsonOfField(7, "total_seconds", pJson["total_seconds"], err, false))
            return false;
    }
    if(pJson.isMember("progress_percentage"))
    {
        if(!validJsonOfField(8, "progress_percentage", pJson["progress_percentage"], err, false))
            return false;
    }
    if(pJson.isMember("last_watched_at"))
    {
        if(!validJsonOfField(9, "last_watched_at", pJson["last_watched_at"], err, false))
            return false;
    }
    if(pJson.isMember("completed_at"))
    {
        if(!validJsonOfField(10, "completed_at", pJson["completed_at"], err, false))
            return false;
    }
    if(pJson.isMember("created_at"))
    {
        if(!validJsonOfField(11, "created_at", pJson["created_at"], err, false))
            return false;
    }
    if(pJson.isMember("updated_at"))
    {
        if(!validJsonOfField(12, "updated_at", pJson["updated_at"], err, false))
            return false;
    }
    return true;
}
bool UserProgress::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                    const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err)
{
    if(pMasqueradingVector.size() != 13)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
      if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
      {
          if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
              return false;
      }
      if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
      {
          if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, false))
              return false;
      }
      if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
      {
          if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, false))
              return false;
      }
      if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
      {
          if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, false))
              return false;
      }
      if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
      {
          if(!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, false))
              return false;
      }
      if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
      {
          if(!validJsonOfField(10, pMasqueradingVector[10], pJson[pMasqueradingVector[10]], err, false))
              return false;
      }
      if(!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11]))
      {
          if(!validJsonOfField(11, pMasqueradingVector[11], pJson[pMasqueradingVector[11]], err, false))
              return false;
      }
      if(!pMasqueradingVector[12].empty() && pJson.isMember(pMasqueradingVector[12]))
      {
          if(!validJsonOfField(12, pMasqueradingVector[12], pJson[pMasqueradingVector[12]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool UserProgress::validJsonOfField(size_t index,
                                    const std::string &fieldName,
                                    const Json::Value &pJson,
                                    std::string &err,
                                    bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 5:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isBool())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 6:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 7:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 8:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 9:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 10:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 11:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 12:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
